package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRov<M extends BaseRov<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRobotYaw(java.lang.Double RobotYaw) {
		set("RobotYaw", RobotYaw);
		return (M)this;
	}
	
	public java.lang.Double getRobotYaw() {
		return getDouble("RobotYaw");
	}

	public M setRobotDepth(java.lang.Double RobotDepth) {
		set("RobotDepth", RobotDepth);
		return (M)this;
	}
	
	public java.lang.Double getRobotDepth() {
		return getDouble("RobotDepth");
	}

	public M setTimes(java.util.Date times) {
		set("times", times);
		return (M)this;
	}
	
	public java.util.Date getTimes() {
		return get("times");
	}

}
