package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRov<M extends BaseRov<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRoll(java.lang.Double roll) {
		set("roll", roll);
		return (M)this;
	}
	
	public java.lang.Double getRoll() {
		return getDouble("roll");
	}

	public M setYaw(java.lang.Double yaw) {
		set("yaw", yaw);
		return (M)this;
	}
	
	public java.lang.Double getYaw() {
		return getDouble("yaw");
	}

	public M setPitch(java.lang.Double pitch) {
		set("pitch", pitch);
		return (M)this;
	}
	
	public java.lang.Double getPitch() {
		return getDouble("pitch");
	}

	public M setDepth(java.lang.Double depth) {
		set("depth", depth);
		return (M)this;
	}
	
	public java.lang.Double getDepth() {
		return getDouble("depth");
	}

	public M setSpeed(java.lang.Double speed) {
		set("speed", speed);
		return (M)this;
	}
	
	public java.lang.Double getSpeed() {
		return getDouble("speed");
	}

	public M setTimes(java.util.Date times) {
		set("times", times);
		return (M)this;
	}
	
	public java.util.Date getTimes() {
		return get("times");
	}

}
