package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDevice<M extends BaseDevice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRovIp(java.lang.String rovIp) {
		set("rov_ip", rovIp);
		return (M)this;
	}
	
	public java.lang.String getRovIp() {
		return getStr("rov_ip");
	}

	public M setCamIp(java.lang.String camIp) {
		set("cam_ip", camIp);
		return (M)this;
	}
	
	public java.lang.String getCamIp() {
		return getStr("cam_ip");
	}

}
