package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKeyboard<M extends BaseKeyboard<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUporDown(java.lang.Double UporDown) {
		set("UporDown", UporDown);
		return (M)this;
	}
	
	public java.lang.Double getUporDown() {
		return getDouble("UporDown");
	}

	public M setLeftorRight(java.lang.Double LeftorRight) {
		set("LeftorRight", LeftorRight);
		return (M)this;
	}
	
	public java.lang.Double getLeftorRight() {
		return getDouble("LeftorRight");
	}

	public M setForwardorBackward(java.lang.Double ForwardorBackward) {
		set("ForwardorBackward", ForwardorBackward);
		return (M)this;
	}
	
	public java.lang.Double getForwardorBackward() {
		return getDouble("ForwardorBackward");
	}

	public M setClimborDive(java.lang.Double ClimborDive) {
		set("ClimborDive", ClimborDive);
		return (M)this;
	}
	
	public java.lang.Double getClimborDive() {
		return getDouble("ClimborDive");
	}

	public M setTimes(java.util.Date times) {
		set("times", times);
		return (M)this;
	}
	
	public java.util.Date getTimes() {
		return get("times");
	}

}
