package com.demo.common.model;

import com.demo.common.model.base.BaseKeyboard;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Keyboard extends BaseKeyboard<Keyboard> {
	public static final Keyboard dao = new Keyboard().dao();
}
