package com.demo.common.model;

import com.demo.common.model.base.BaseRov;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rov extends BaseRov<Rov> {
	public static final Rov dao = new Rov().dao();
}
